#!/usr/bin/env python3
"""Vendor the generated Rust code for the interface packages that rclrs needs.

Reads the generated crates out of a sourced ROS 2 workspace, writes `src/shim/`
and the `src/shim.rs` that wraps them. Both are meant to be committed. Only
`use_ros_shim` compiles any of it.

    ./vendor_interfaces.py

The workspace has to be one where rosidl_generator_rs has run, because a plain
ROS 2 installation ships no Rust.
"""

import argparse
import os
import shutil
import subprocess
from pathlib import Path

# The packages rclrs uses, plus the packages those depend on.
VENDORED_PACKAGES = [
    "action_msgs",
    "builtin_interfaces",
    "rcl_interfaces",
    "rosgraph_msgs",
    "unique_identifier_msgs",
]

SRC_DIR = Path(__file__).parent / "src"
SHIM_DIR = SRC_DIR / "shim"
SHIM_RS = SRC_DIR / "shim.rs"


def get_args():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--prefix-path",
        default=os.environ.get("AMENT_PREFIX_PATH"),
        help="where to look for the generated crates, defaults to AMENT_PREFIX_PATH",
    )
    parser.add_argument(
        "--distro",
        default=os.environ.get("ROS_DISTRO"),
        help="recorded in the file headers, defaults to ROS_DISTRO",
    )

    args = parser.parse_args()

    if not args.prefix_path:
        parser.error("AMENT_PREFIX_PATH is not set, source a ROS 2 workspace first")
    if not args.distro:
        parser.error("ROS_DISTRO is not set, source a ROS 2 workspace first")

    args.prefixes = [Path(p) for p in args.prefix_path.split(os.pathsep) if p]

    return args


def generated_dir(prefixes: list[Path], package: str) -> Path:
    """Find a package's generated crate, taking the first prefix that has it."""
    for prefix in prefixes:
        candidate = prefix / "share" / package / "rust"
        if (candidate / "src").is_dir():
            return candidate

    raise SystemExit(
        f"No generated Rust for {package} on AMENT_PREFIX_PATH. Source a "
        "workspace where rosidl_generator_rs has run over it."
    )


def package_version(generated: Path) -> str:
    """Read the version from a generated crate's Cargo.toml."""
    manifest = generated / "Cargo.toml"

    for line in manifest.read_text().splitlines():
        if line.startswith("version"):
            return line.split("=", 1)[1].strip().strip('"')

    raise RuntimeError(f"No version found in {manifest}")


def add_header(source: Path, package: str, distro: str, version: str) -> None:
    """Mark a copied file, so nobody mistakes it for code this crate owns."""
    header = (
        f"// Copied verbatim from the generated Rust code for `{package}` {version},\n"
        f"// built from the `{distro}` distro. Do not edit. Run `vendor_interfaces.py`\n"
        f"// to refresh it.\n\n"
    )
    source.write_text(header + source.read_text())


def module_tree(package: str) -> str:
    """Mirror the module structure of the generated crate's `lib.rs`.

    `use crate::*` stands in for the dependency imports that `lib.rs` would have
    brought in, since the generated code names sibling packages directly.
    """
    modules = []
    for source in sorted((SHIM_DIR / package).glob("*.rs")):
        stem = source.stem
        modules.append(
            f'pub mod {stem} {{ use crate::*; include!("shim/{package}/{stem}.rs");'
            f' pub mod rmw {{ use crate::*; include!("shim/{package}/{stem}/rmw.rs"); }} }}'
        )

    return (
        f"#[allow(warnings, clippy::all)]\npub mod {package} {{ {' '.join(modules)} }}"
    )


def main():
    args = get_args()
    generated = {p: generated_dir(args.prefixes, p) for p in VENDORED_PACKAGES}
    versions = {p: package_version(d) for p, d in generated.items()}

    if SHIM_DIR.exists():
        shutil.rmtree(SHIM_DIR)
    SHIM_DIR.mkdir(parents=True)

    for package, source in generated.items():
        shutil.copytree(source / "src", SHIM_DIR / package)
        # `lib.rs` is replaced by the module tree in `shim.rs`.
        (SHIM_DIR / package / "lib.rs").unlink()
        for copied in (SHIM_DIR / package).rglob("*.rs"):
            add_header(copied, package, args.distro, versions[package])

    header = [
        "//! Generated by `vendor_interfaces.py`. Do not edit by hand.",
        "//!",
        f"//! Copied from a `{args.distro}` workspace:",
        "//!",
    ] + [f"//! - `{p}` {v}" for p, v in versions.items()]

    body = [module_tree(package) for package in VENDORED_PACKAGES]
    SHIM_RS.write_text("\n".join(header) + "\n\n" + "\n\n".join(body) + "\n")

    # `cargo fmt` does not reach this code through `include!()`.
    for path in sorted([SHIM_RS, *SHIM_DIR.rglob("*.rs")]):
        subprocess.check_call(["rustfmt", "--edition", "2021", str(path)])


if __name__ == "__main__":
    main()
