//! Generated by `vendor_interfaces.py`. Do not edit by hand.
//!
//! Copied from a `humble` workspace:
//!
//! - `action_msgs` 1.2.3
//! - `builtin_interfaces` 1.2.3
//! - `rcl_interfaces` 1.2.3
//! - `rosgraph_msgs` 1.2.3
//! - `unique_identifier_msgs` 2.2.1

#[allow(warnings, clippy::all)]
pub mod action_msgs {
    pub mod msg {
        use crate::*;
        include!("shim/action_msgs/msg.rs");
        pub mod rmw {
            use crate::*;
            include!("shim/action_msgs/msg/rmw.rs");
        }
    }
    pub mod srv {
        use crate::*;
        include!("shim/action_msgs/srv.rs");
        pub mod rmw {
            use crate::*;
            include!("shim/action_msgs/srv/rmw.rs");
        }
    }
}

#[allow(warnings, clippy::all)]
pub mod builtin_interfaces {
    pub mod msg {
        use crate::*;
        include!("shim/builtin_interfaces/msg.rs");
        pub mod rmw {
            use crate::*;
            include!("shim/builtin_interfaces/msg/rmw.rs");
        }
    }
}

#[allow(warnings, clippy::all)]
pub mod rcl_interfaces {
    pub mod msg {
        use crate::*;
        include!("shim/rcl_interfaces/msg.rs");
        pub mod rmw {
            use crate::*;
            include!("shim/rcl_interfaces/msg/rmw.rs");
        }
    }
    pub mod srv {
        use crate::*;
        include!("shim/rcl_interfaces/srv.rs");
        pub mod rmw {
            use crate::*;
            include!("shim/rcl_interfaces/srv/rmw.rs");
        }
    }
}

#[allow(warnings, clippy::all)]
pub mod rosgraph_msgs {
    pub mod msg {
        use crate::*;
        include!("shim/rosgraph_msgs/msg.rs");
        pub mod rmw {
            use crate::*;
            include!("shim/rosgraph_msgs/msg/rmw.rs");
        }
    }
}

#[allow(warnings, clippy::all)]
pub mod unique_identifier_msgs {
    pub mod msg {
        use crate::*;
        include!("shim/unique_identifier_msgs/msg.rs");
        pub mod rmw {
            use crate::*;
            include!("shim/unique_identifier_msgs/msg/rmw.rs");
        }
    }
}
